---
title: "Data Analyses"
author: "Bocheng Zhang"
date: "2021/4/11"
output: html_document
---

## Load Datasets and Packages
```{r}
library(readr)
China <- read_csv("Freshman_China.csv")
India <- read_csv("Freshman_India.csv")
Analyses <- read_csv("DID.csv")

library(tidyverse)
library(stargazer)
```

## Data cleaning and manipulation
```{r}
China<-filter(China,between(Year,2001,2020))
India<-filter(India,between(Year,2001,2020))

Analyses<-mutate(Analyses,C=ifelse(Country_India=="China",1,0))
Analyses<-mutate(Analyses,Y=ifelse(Year>=2018,1,0))
Analyses<-mutate(Analyses,War=ifelse(Country_India=="China" & Year>=2018,1,0))

Analyses<-mutate(Analyses,C2=ifelse(Country_India=="China",1,0))
Analyses<-mutate(Analyses,Y2=ifelse(Year>=2019,1,0))
Analyses<-mutate(Analyses,War2=ifelse(Country_India=="China" & Year>=2019,1,0))
```

## Graphs
```{r}
ggplot(data=China,mapping = aes(x=Year,y=Fall))+geom_line()+geom_point()

ggplot(data=Analyses,mapping = aes(x=Year,y=Enrollment_India,color=Country_India))+geom_line()+geom_point()

ggplot(data=Analyses,mapping = aes(x=Year,y=Enrollment_Canada,color=Country_Canada))+geom_line()+geom_point()
```

## Difference-in-Difference Model
```{r}
## Model with India as the counterfactual (treatment from 2018)
Model1<-lm(Enrollment_India~C+Y+War,Analyses)
## Model for the all undergraduates (treatment from 2018)
Model2<-lm(Enrollment_Canada~C+Y+War,Analyses)

## Model with India as the counterfactual (treatment from 2019)
Model3<-lm(Enrollment_India~C2+Y2+War2,Analyses)
## Model for the all undergraduates (treatment from 2019)
Model4<-lm(Enrollment_Canada~C2+Y2+War2,Analyses)
```

## Regression Tables
```{r}
stargazer(Model1,Model2,title = "Difference-in-Difference Estimates (Treatment from 2018)",type="text",digits=3,out="table1.htm",dep.var.labels = c("Freshmen Enrollment","Freshmen Enrollment"),covariate.labels = c("Country","Year","US-China Trade War"))

stargazer(Model3,Model4,title = "Difference-in-Difference Estimates (Treatment from 2019)",type="text",digits=3,out="table2.htm",dep.var.labels = c("Freshmen Enrollment","Freshmen Enrollment"),covariate.labels = c("Country","Year","US-China Trade War"))
```




